name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode 16
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
    
    - name: Check Xcode version
      run: xcodebuild -version
    
    - name: List installed simulators
      run: xcrun simctl list devices available
    
    - name: Run lint command
      run: |
        cd scripts
        swift run tools lint-format