name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-26
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0'
    
    - name: Check Xcode version
      run: xcodebuild -version
    
    - name: List installed simulators
      run: xcrun simctl list devices available
    
    - name: Run lint command
      run: |
        cd scripts
        swift run tools lint-format

    - name: Build project
      run: |
        swift run tools xcode-build clean-build -c Release